In [12]:
from primer_design_assistant import _calc_tm_with_primer3, parse_fasta
parse_fasta(r"C:\Users\jdejo\Downloads\sequence_Mtuberculosis_H37Rv.fasta")[0]

SeqRecord(seq=Seq('TTGACCGATGACCCCGGTTCAGGCTTCACCACAGTGTGGAACGCGGTCGTCTCC...TCG'), id='NC_000962.3', name='NC_000962.3', description='NC_000962.3 Mycobacterium tuberculosis H37Rv, complete genome', dbxrefs=[])

In [42]:
from primer_design_assistant import parse_fasta, _calc_tm_with_primer3

rec = parse_fasta(r"C:\Users\jdejo\Downloads\sequence_Mtuberculosis_H37Rv.fasta")[0]
primer = str(rec.seq[100:120])
_calc_tm_with_primer3(primer)

60.9386367865672

In [ ]:
from primer_design_assistant import parse_fasta, design_primer_pairs

rec = parse_fasta(r"C:\Users\jdejo\Downloads\sequence_Mtuberculosis_H37Rv.fasta")[0]

df = design_primer_pairs(
    str(rec.seq),          
    primer_length=18,
    tm_min=50,
    tm_max=75,
    min_amplicon=100,
    max_amplicon=600,
    top_n=20,
    max_candidates=500
)
df.head()

,Sequence_ID,forward_start,forward_seq,forward_tm,reverse_start,reverse_seq,reverse_tm,amplicon_length,tm_diff,avg_tm
0,seq_1,1876930,GCGGCCGGCGTGCCCGGC,74.996324,1877133,GCGCCGGGTGCCCCGCGC,74.996324,221,0.0,74.996324
1,seq_1,1876932,GGCCGGCGTGCCCGGCGC,74.996324,1877133,GCGCCGGGTGCCCCGCGC,74.996324,219,0.0,74.996324
2,seq_1,1876933,GCCGGCGTGCCCGGCGCC,74.996324,1877133,GCGCCGGGTGCCCCGCGC,74.996324,218,0.0,74.996324

In [27]:
df = design_primer_pairs(str(rec.seq), tm_min=0, tm_max=100, primer_length=18, max_candidates=500)
df

,Sequence_ID,forward_start,forward_seq,forward_tm,reverse_start,reverse_seq,reverse_tm,amplicon_length,tm_diff,avg_tm
0,seq_1,746914,GGCCGCGCGCCGCCGCGC,78.272530,747707,GCGCCGCGGCGCCGCGGC,78.272530,811,0.0,78.272530
1,seq_1,746915,GCCGCGCGCCGCCGCGCC,78.272530,747707,GCGCCGCGGCGCCGCGGC,78.272530,810,0.0,78.272530
2,seq_1,150338,GCGGCGGCGCCGGCGGCG,77.799552,150638,CCGCGCCGCCGGCCGCGC,77.799552,318,0.0,77.799552
3,seq_1,150338,GCGGCGGCGCCGGCGGCG,77.799552,150637,CGCGCCGCCGGCCGCGCC,77.799552,317,0.0,77.799552
4,seq_1,150338,GCGGCGGCGCCGGCGGCG,77.799552,150599,CGCCGGCGCCGCCGGCGC,77.799552,279,0.0,77.799552
5,seq_1,150338,GCGGCGGCGCCGGCGGCG,77.799552,150596,CGGCGCCGCCGGCGCCGC,77.799552,276,0.0,77.799552
6,seq_1,150338,GCGGCGGCGCCGGCGGCG,77.799552,150594,GCGCCGCCGGCGCCGCCG,77.799552,274,0.0,77.799552
7,seq_1,244526,GGCGCCGCCGCCGCGGCG,77.799552,244853,GCCGCGCCGGCGGCGCCG,77.799552,345,0.0,77.799552
8,seq_1,244527,GCGCCGCCGCCGCGGCGG,77.799552,244853,GCCGCGCCGGCGGCGCCG,77.799552,344,0.0,77.799552
9,seq_1,244528,CGCCGCCGCCGCGGCGGC,77.799552,244853,GCCGCGCCGGCGGCGCCG,77.799552,343,0.0,77.799552

In [28]:
df = design_primer_pairs(str(rec.seq[100000:120000]), primer_length=18, tm_min=50, tm_max=75, max_candidates=500)
df

,Sequence_ID,forward_start,forward_seq,forward_tm,reverse_start,reverse_seq,reverse_tm,amplicon_length,tm_diff,avg_tm
0,seq_1,1554,GGCGGCCGCGGTGGGCGC,74.996324,2191,GGCGTGGCGCCGGGCCGC,74.996324,655,0.0,74.996324
1,seq_1,1555,GCGGCCGCGGTGGGCGCC,74.996324,2191,GGCGTGGCGCCGGGCCGC,74.996324,654,0.0,74.996324
2,seq_1,1556,CGGCCGCGGTGGGCGCCG,74.608870,2192,CGGCGTGGCGCCGGGCCG,74.608870,654,0.0,74.608870
3,seq_1,14610,GTGGGGCCGGCCCGGGCG,73.780759,15273,CCCGCCCGGGCGCCCACC,73.780759,681,0.0,73.780759
4,seq_1,1557,GGCCGCGGTGGGCGCCGA,73.557889,2193,TCGGCGTGGCGCCGGGCC,73.557889,654,0.0,73.557889
5,seq_1,16902,GCGCGCTGCCGGTCGCGG,72.545382,17423,CGCCGCTCGCACCGCGGC,72.545382,539,0.0,72.545382
6,seq_1,4159,GCAGGGTGCCGCCGCCGG,71.932257,4671,CGCCCACCTGCCCGCCGC,71.932257,530,0.0,71.932257
7,seq_1,4159,GCAGGGTGCCGCCGCCGG,71.932257,4670,GCCCACCTGCCCGCCGCG,71.932257,529,0.0,71.932257
8,seq_1,11946,CCGGCGACCTGGCGGCGC,71.828162,12626,CCGGGTCGCCGCGGCAGC,71.828162,698,0.0,71.828162
9,seq_1,17128,CGCGCGGGTGGCCGGCTC,71.828162,17684,CGGCCGCGCGTCAGGGCC,71.828162,574,0.0,71.828162

In [ ]:
from primer_design_assistant import design_primer_pairs

df = design_primer_pairs(
    r"C:\Users\jdejo\Downloads\sequence_Mtuberculosis_H37Rv.fasta",
    primer_length=18,
    tm_min=50, tm_max=75,
    min_amplicon=100, max_amplicon=600,
    top_n=5,
    max_candidates=50000
)


df

,Sequence_ID,forward_start,forward_seq,forward_tm,reverse_start,reverse_seq,reverse_tm,amplicon_length,tm_diff,avg_tm
0,NC_000962.3,93072,GCCGGCGCCGCGCCCACC,74.996324,93526,GGCGCCCACCGCGCGGGC,74.996324,472,0.0,74.996324
1,NC_000962.3,93072,GCCGGCGCCGCGCCCACC,74.996324,93525,GCGCCCACCGCGCGGGCC,74.996324,471,0.0,74.996324
2,NC_000962.3,150184,GCCGGCGGCGGCGGTGGC,74.996324,150646,GGCACCGCCCGCGCCGCC,74.996324,480,0.0,74.996324
3,NC_000962.3,150184,GCCGGCGGCGGCGGTGGC,74.996324,150589,GCCGGCGCCGCCGTGCCC,74.996324,423,0.0,74.996324
4,NC_000962.3,150184,GCCGGCGGCGGCGGTGGC,74.996324,150469,GGCGCCACCCGCGGCGCC,74.996324,303,0.0,74.996324

In [ ]:
from primer_design_assistant import design_primer_pairs

df = design_primer_pairs(
    r"C:\Users\jdejo\Downloads\sequence_Mtuberculosis_H37Rv.fasta",
    r"C:\Users\jdejo\Downloads\sequence_Ecoli_strK12_substrMG1655.fasta",
    primer_length=18,
    tm_min=50, tm_max=75,
    min_amplicon=100, max_amplicon=600,
    top_n=5,
    max_candidates=300
)
df.head()

,Sequence_ID,forward_start,forward_seq,forward_tm,reverse_start,reverse_seq,reverse_tm,amplicon_length,tm_diff,avg_tm
0,U00096.3,3232448,ACGCCCGTGCCGCGCGGC,74.531808,3232839,GCCCACGCGCCGCCGCGT,74.531808,409,0.000000,74.531808
1,U00096.3,3232451,CCCGTGCCGCGCGGCGCA,74.522276,3232840,TGCCCACGCGCCGCCGCG,74.522276,407,0.000000,74.522276
2,U00096.3,3232448,ACGCCCGTGCCGCGCGGC,74.531808,3232840,TGCCCACGCGCCGCCGCG,74.522276,410,0.009532,74.527042
3,U00096.3,3232451,CCCGTGCCGCGCGGCGCA,74.522276,3232839,GCCCACGCGCCGCCGCGT,74.531808,406,0.009532,74.527042
4,U00096.3,723368,GCGGCGCGAGGCCGGGCG,74.599673,723597,CCGCGCAGCGGCGCGGCT,74.551547,247,0.048127,74.575610